In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
np.random.seed(29)

In [104]:
ntrials=10000
nrows=10000

In [103]:
outcomes = [1,2,3,4,5,6]
rolls =np.random.choice(outcomes,size = (10000,2))
rolls_df = pd.DataFrame(rolls)
(rolls_df[0] == rolls_df[1]).mean()

0.1648

In [112]:
coins = 8

coin = np.random.choice(['T','H'],ntrials * coins).reshape(ntrials,coins)
coindf = pd.DataFrame(coin)
numcoins = coindf.apply(pd.value_counts, axis=1)
(numcoins.H == 3).mean()

0.2227

In [113]:
(numcoins.H > 3).mean()

0.6314

In [118]:
webd = .75
ds = .25
cols = 2

cohorts = np.random.choice(['WD',"WD","WD","DS"],size = (ntrials,cols))
cdata = cohorts == "DS"
success = cdata.sum(axis =1)==2
success.mean()

0.0614

In [60]:
pttotal=17
nsimulation=5
pt = np.random.normal(3,1.5,size = (nsimulation,5))
pt
#

array([[1.12090051, 3.13941239, 5.25320179, 3.79720483, 5.32175627],
       [1.46847466, 3.4966166 , 5.76840759, 2.39816124, 4.2120235 ],
       [3.50719554, 1.82892437, 3.54646936, 2.67310401, 2.69409454],
       [1.30459068, 4.30591981, 1.93564727, 2.90300463, 4.6385189 ],
       [2.11346253, 2.15669483, 3.72802414, 3.70754715, 1.89180494]])

In [63]:
week = pt.sum(axis=1)
week

array([18.63247578, 17.34368359, 14.24978782, 15.0876813 , 13.59753358])

In [120]:
(week >=17).mean()

0.4

In [67]:
mh = np.random.normal(178,8, size = (nsimulation,5))
wh = np.random.normal(170,6, size = (nsimulation,5))

In [122]:
(wh>mh).mean()

0.2

In [125]:
outcome = ['S','F']
students = 50

In [131]:
downloads = np.random.choice(outcome,size = (ntrials, students),p=[249/250,1/250])
((downloads=='S').sum(axis=1)==50).mean()

0.8181

In [132]:
((downloads=='S').sum(axis=1)==100).mean()

0.0

In [140]:
(bools.sum(axis=(1))<150).mean()

1.0

In [141]:
(bools.sum(axis=(1))==450).mean()

0.0

In [143]:
trucks = np.random.choice([0,1],size = (ntrials,3),p =[.3,.7])

In [145]:
(trucks.sum(axis=1)==0).mean()

0.0264

In [146]:
(trucks.sum(axis=1)>=1).mean()

0.9736

In [148]:
weektruck = np.random.choice([0,1],size = (ntrials,8),p =[.3,.7])
(weektruck.sum(axis=1)>0).mean()

1.0

In [149]:
bith = range(0,366)
stu=23

In [150]:
birthday = np.random.choice(bith,size = (ntrials,23))

In [151]:
birthday

array([[ 29,  95, 315, ..., 233,  40, 352],
       [270, 112, 232, ..., 120, 225, 270],
       [361, 224,  51, ...,  89, 250, 193],
       ...,
       [107,   8,  31, ..., 362, 228,  40],
       [237, 228, 242, ...,  27,  84, 256],
       [279, 255, 180, ..., 250, 253,  48]])

In [152]:
birthdaydf = pd.DataFrame(birthday)

In [155]:
(birthdaydf.nunique(axis=1) <23).mean()

0.5119

In [157]:
birthday = np.random.choice(bith,size = (ntrials,40))

In [160]:
(birthdaydf.nunique(axis=1) <40).mean()

1.0